apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ai-backend-deployment.yaml
  - ai-backend-service.yaml
  - web-backend-deployment.yaml
  - web-backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
