apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: desk-ai
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: desk-ai
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
